name: Test Trigger

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-format:
    uses: ./.github/workflows/code-formatting-check.yml
    secrets: inherit
    with:
      python_formatting: false
      shell_formatting: false
      yaml_formatting: false
